name       : pidgin-otr
version    : 4.0.2
release    : 2
source     :
    - https://otr.cypherpunks.ca/pidgin-otr-4.0.2.tar.gz : f4b59eef4a94b1d29dbe0c106dd00cdc630e47f18619fc754e5afbf5724ebac4
license    : GPL-2.0
summary    : Pidgin OTR Plugin
description: |
    Off-the-Record Messaging plugin for Pidgin.
builddeps  :
    - pkgconfig(libotr)
    - pkgconfig(pidgin)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(purple)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
