name       : pidgin-otr
version    : 4.0.1
release    : 1
source     :
    - https://otr.cypherpunks.ca/pidgin-otr-4.0.1.tar.gz : 1b781f48c27bcc9de3136c0674810df23f7d6b44c727dbf4dfb24067909bf30a
license    : GPL-2.0
summary    : Pidgin OTR Plugin
description: |
    Off-the-Record Messaging plugin for Pidgin.
builddeps  :
    - pkgconfig(libotr)
    - pkgconfig(pidgin)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(purple)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
